### ISSUE TITLE
Use standard colors for common values

### ISSUE THREAD

**Issue by curran** [unhcr/dataviz-somalia-prmn#26]
For example, these colors are semi-standardised in certain parts of UNHCR

 * Drought `rgb(247,148,29)`
 * Conflict/Insecurity `rgb(231,100,106)`
 * Other `rgb(160,123,94)`
 * Flood `rgb(201,116,162)`

HT @mugodavid

Related to https://github.com/unhcr/dataviz-styleguide/issues/63

**Comment by matthewsmawfield** [comment]
done
